# Generated by Django 3.2.9 on 2021-12-03 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aqar_agencies', '0002_auto_20211128_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_picture'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='verification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
    ]
