# Generated by Django 3.2.7 on 2021-12-05 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aqar_agencies', '0003_auto_20211203_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='phone_number',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='aqar_agencies.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='aqar_agencies.agency'),
        ),
    ]
