# Generated by Django 3.2.7 on 2021-12-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar_agencies', '0004_auto_20211205_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
