# Generated by Django 3.2.7 on 2021-12-05 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aqar_agencies', '0005_areamanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AreaManager',
        ),
    ]
