# Generated by Django 3.2.7 on 2021-12-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar_agencies', '0006_delete_areamanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
